[project]
name = "micropython-macos-test1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "micropython-unix-stubs==1.24.1.post2",
    "mpremote>=1.24.1",
]
